---
title: "Teaching"
description: |
  This section discusses my teaching experience.
---

<style>
d-title {
 display:none;
}
</style>

<br>
<br>

### Teaching

I currently teach on the following courses

  * [**Data Visualisation with ggplot2 to Postgraduate Students**](https://www.tudublin.ie/study/postgraduate/courses/data-science/) (100%)
  * [**Manufacturing Technology to 4th Year Pharmaceutical Science**](https://www.tudublin.ie/study/undergraduate/courses/pharmaceutical-science-tu876/) (50%)
  * [**Computer Measurement Systems to 2nd Year Bioanalysis**](https://www.tudublin.ie/study/undergraduate/courses/bioanalysis-tu760/) (33%)
  * [**Principles of Pnysics to 1st Year Sports Science**](https://www.tudublin.ie/study/undergraduate/courses/sports-science-and-health-tu936/) (100%)
  
### Laboratory Resources

The undergraduate courses above use the following laboratory resources:

- Manufacturing Technology  
  - we use Process Simulator programme [UniSim490 from Honeywell](https://www.honeywellprocess.com/en-US/explore/products/advanced-applications/unisim/Pages/default.aspx)
  - examples of the labs from 2019 are given [here](assets/ManTech_Lab_Manual_2019.pdf)  
- Computer Measurement Systems  
  - we use [LabVIEW from National Instruments](https://www.ni.com/en-ie/shop/labview.html) to make virtual instruments.
  - some of the laboratory assignments we do can be seen [here](assets/LabVIEW_2021.pdf) 
- Principals of Physics  
  - during COVID19 lockdown we put together a series of online experiments for the students  
  - these can be seen here
  
  
### Final Year Projects

I'm also involved in final year projects with the pharmaceutical science students. These have been:

- **2021**  
  - The Wider Impact of COVID19 on Public Health in Ireland  
  - The Genomics of SARS-coranavirus-2  
  - The Association of Telomere Length and Schizophrenia Related SNP's  
- **2020**  
  - Investigation of Breast Cancer Pharmacogenomics Data using the PharmcoGx Bioconductor Package  
  - Single Cell RNASeq Analysis of Transciptomic Data using the scrattch Package  
- **2019**  
  - Association of Tuberculosis and HIV in Africa  
- **2018**    
  - Investigation of Breast Cancer Pharmacogenomics Data using the PharmcoGx Bioconductor Package  
  - Investigation of Autism Genes by Examining Gene Expression across Different Areas of Healthy Brains  
  - Predict whether a Cancer is Benign or Malignant using the Wisconsin Breast Cancer Diagnostic Dataset  
- **2018**    
  - Investigation of Schizophrenia Genes by Examining Gene Expression across Different Areas of Healthy Brains  
  - Classification of Acute Lymphocytic Leukemia using R Programming Techniques 
- **2017**    
  - Asthma Clinical Trial Machine Learning using the CAMP Dataset  
- **2016**    
  - T-Cell Acute Lymphocytic Leukemia Microarray Sample Classification using R Programming Techniques  
  - Computer Simulation of Heat Integration of Process Streams in the Styrene Process using UniSim430 
  - Computer Simulation of Heat Integration of Process Streams in the Propylene Glycol Process using UniSim430  